receivers:
  otlp: # the OTLP receiver the app is sending metrics to
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  prometheusremotewrite: # the PRW exporter, to ingest metrics to backend
    endpoint: http://mimir:9009/api/v1/push

service:
  pipelines:
    metrics/prod:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]

extensions:
 health_check:
 pprof:
   endpoint: 0.0.0.0:1777
 zpages:
   endpoint: 0.0.0.0:55679
